/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JamaahIndexRouteImport } from './routes/jamaah.index'
import { Route as ReferralRouteImport } from './routes/referral'
import { Route as KomisiRouteImport } from './routes/komisi'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JamaahIndexRoute = JamaahIndexRouteImport.update({
  id: '/jamaah/',
  path: '/jamaah',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralRoute = ReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => rootRouteImport,
} as any)
const KomisiRoute = KomisiRouteImport.update({
  id: '/komisi',
  path: '/komisi',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/jamaah/': typeof JamaahIndexRoute
  '/referral': typeof ReferralRoute
  '/komisi': typeof KomisiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/jamaah': typeof JamaahIndexRoute
  '/referral': typeof ReferralRoute
  '/komisi': typeof KomisiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/jamaah/': typeof JamaahIndexRoute
  '/referral': typeof ReferralRoute
  '/komisi': typeof KomisiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/jamaah/'
    | '/referral'
    | '/komisi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/jamaah'
    | '/referral'
    | '/komisi'
  id:
    | '__root__'
    | '/'
    | '/jamaah/'
    | '/referral'
    | '/komisi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JamaahIndexRoute: typeof JamaahIndexRoute
  ReferralRoute: typeof ReferralRoute
  KomisiRoute: typeof KomisiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jamaah/': {
      id: '/jamaah/'
      path: '/jamaah'
      fullPath: '/jamaah/'
      preLoaderRoute: typeof JamaahIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referral': {
      id: '/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof ReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/komisi': {
      id: '/komisi'
      path: '/komisi'
      fullPath: '/komisi'
      preLoaderRoute: typeof KomisiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JamaahIndexRoute: JamaahIndexRoute,
  ReferralRoute: ReferralRoute,
  KomisiRoute: KomisiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}