/* eslint-disable */
// @ts-nocheck
// This file was automatically generated by TanStack Router.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

const rootRouteChildren = {
  IndexRoute: IndexRoute,
}

export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)
