/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgenRouteImport } from './routes/agen'
import { Route as AgensiRouteImport } from './routes/agensi'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as CsRouteImport } from './routes/cs'
import { Route as DokumenRouteImport } from './routes/dokumen'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as GaleriRouteImport } from './routes/galeri'
import { Route as HakAksesRouteImport } from './routes/hak-akses'
import { Route as HotelRouteImport } from './routes/hotel'
import { Route as ItinerariRouteImport } from './routes/itinerari'
import { Route as KeberangkatanRouteImport } from './routes/keberangkatan'
import { Route as KomisiRouteImport } from './routes/komisi'
import { Route as LaporanRouteImport } from './routes/laporan'
import { Route as LaporanKeuanganRouteImport } from './routes/laporan-keuangan'
import { Route as LoyalitasRouteImport } from './routes/loyalitas'
import { Route as PanduanRouteImport } from './routes/panduan'
import { Route as PembayaranRouteImport } from './routes/pembayaran'
import { Route as PenerbanganRouteImport } from './routes/penerbangan'
import { Route as PengaturanRouteImport } from './routes/pengaturan'
import { Route as PengeluaranRouteImport } from './routes/pengeluaran'
import { Route as PengumumanRouteImport } from './routes/pengumuman'
import { Route as PortalJamaahRouteImport } from './routes/portal-jamaah'
import { Route as ReferralRouteImport } from './routes/referral'
import { Route as SertifikatRouteImport } from './routes/sertifikat'
import { Route as TourLeaderRouteImport } from './routes/tour-leader'
import { Route as TransportasiRouteImport } from './routes/transportasi'
import { Route as VisaRouteImport } from './routes/visa'
import { Route as JamaahIndexRouteImport } from './routes/jamaah.index'
import { Route as JamaahIdRouteImport } from './routes/jamaah.$id'
import { Route as PaketIndexRouteImport } from './routes/paket.index'
import { Route as PaketIdRouteImport } from './routes/paket.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenRoute = AgenRouteImport.update({
  id: '/agen',
  path: '/agen',
  getParentRoute: () => rootRouteImport,
} as any)
const AgensiRoute = AgensiRouteImport.update({
  id: '/agensi',
  path: '/agensi',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const CsRoute = CsRouteImport.update({
  id: '/cs',
  path: '/cs',
  getParentRoute: () => rootRouteImport,
} as any)
const DokumenRoute = DokumenRouteImport.update({
  id: '/dokumen',
  path: '/dokumen',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriRoute = GaleriRouteImport.update({
  id: '/galeri',
  path: '/galeri',
  getParentRoute: () => rootRouteImport,
} as any)
const HakAksesRoute = HakAksesRouteImport.update({
  id: '/hak-akses',
  path: '/hak-akses',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelRoute = HotelRouteImport.update({
  id: '/hotel',
  path: '/hotel',
  getParentRoute: () => rootRouteImport,
} as any)
const ItinerariRoute = ItinerariRouteImport.update({
  id: '/itinerari',
  path: '/itinerari',
  getParentRoute: () => rootRouteImport,
} as any)
const KeberangkatanRoute = KeberangkatanRouteImport.update({
  id: '/keberangkatan',
  path: '/keberangkatan',
  getParentRoute: () => rootRouteImport,
} as any)
const KomisiRoute = KomisiRouteImport.update({
  id: '/komisi',
  path: '/komisi',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanRoute = LaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanKeuanganRoute = LaporanKeuanganRouteImport.update({
  id: '/laporan-keuangan',
  path: '/laporan-keuangan',
  getParentRoute: () => rootRouteImport,
} as any)
const LoyalitasRoute = LoyalitasRouteImport.update({
  id: '/loyalitas',
  path: '/loyalitas',
  getParentRoute: () => rootRouteImport,
} as any)
const PanduanRoute = PanduanRouteImport.update({
  id: '/panduan',
  path: '/panduan',
  getParentRoute: () => rootRouteImport,
} as any)
const PembayaranRoute = PembayaranRouteImport.update({
  id: '/pembayaran',
  path: '/pembayaran',
  getParentRoute: () => rootRouteImport,
} as any)
const PenerbanganRoute = PenerbanganRouteImport.update({
  id: '/penerbangan',
  path: '/penerbangan',
  getParentRoute: () => rootRouteImport,
} as any)
const PengaturanRoute = PengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => rootRouteImport,
} as any)
const PengeluaranRoute = PengeluaranRouteImport.update({
  id: '/pengeluaran',
  path: '/pengeluaran',
  getParentRoute: () => rootRouteImport,
} as any)
const PengumumanRoute = PengumumanRouteImport.update({
  id: '/pengumuman',
  path: '/pengumuman',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalJamaahRoute = PortalJamaahRouteImport.update({
  id: '/portal-jamaah',
  path: '/portal-jamaah',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralRoute = ReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => rootRouteImport,
} as any)
const SertifikatRoute = SertifikatRouteImport.update({
  id: '/sertifikat',
  path: '/sertifikat',
  getParentRoute: () => rootRouteImport,
} as any)
const TourLeaderRoute = TourLeaderRouteImport.update({
  id: '/tour-leader',
  path: '/tour-leader',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportasiRoute = TransportasiRouteImport.update({
  id: '/transportasi',
  path: '/transportasi',
  getParentRoute: () => rootRouteImport,
} as any)
const VisaRoute = VisaRouteImport.update({
  id: '/visa',
  path: '/visa',
  getParentRoute: () => rootRouteImport,
} as any)
const JamaahIndexRoute = JamaahIndexRouteImport.update({
  id: '/jamaah/',
  path: '/jamaah',
  getParentRoute: () => rootRouteImport,
} as any)
const JamaahIdRoute = JamaahIdRouteImport.update({
  id: '/jamaah/$id',
  path: '/jamaah/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PaketIndexRoute = PaketIndexRouteImport.update({
  id: '/paket/',
  path: '/paket',
  getParentRoute: () => rootRouteImport,
} as any)
const PaketIdRoute = PaketIdRouteImport.update({
  id: '/paket/$id',
  path: '/paket/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agen': typeof AgenRoute
  '/agensi': typeof AgensiRoute
  '/auth': typeof AuthRoute
  '/booking': typeof BookingRoute
  '/crm': typeof CrmRoute
  '/cs': typeof CsRoute
  '/dokumen': typeof DokumenRoute
  '/feedback': typeof FeedbackRoute
  '/galeri': typeof GaleriRoute
  '/hak-akses': typeof HakAksesRoute
  '/hotel': typeof HotelRoute
  '/itinerari': typeof ItinerariRoute
  '/keberangkatan': typeof KeberangkatanRoute
  '/komisi': typeof KomisiRoute
  '/laporan': typeof LaporanRoute
  '/laporan-keuangan': typeof LaporanKeuanganRoute
  '/loyalitas': typeof LoyalitasRoute
  '/panduan': typeof PanduanRoute
  '/pembayaran': typeof PembayaranRoute
  '/penerbangan': typeof PenerbanganRoute
  '/pengaturan': typeof PengaturanRoute
  '/pengeluaran': typeof PengeluaranRoute
  '/pengumuman': typeof PengumumanRoute
  '/portal-jamaah': typeof PortalJamaahRoute
  '/referral': typeof ReferralRoute
  '/sertifikat': typeof SertifikatRoute
  '/tour-leader': typeof TourLeaderRoute
  '/transportasi': typeof TransportasiRoute
  '/visa': typeof VisaRoute
  '/jamaah/$id': typeof JamaahIdRoute
  '/paket/$id': typeof PaketIdRoute
  '/jamaah/': typeof JamaahIndexRoute
  '/paket/': typeof PaketIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agen': typeof AgenRoute
  '/agensi': typeof AgensiRoute
  '/auth': typeof AuthRoute
  '/booking': typeof BookingRoute
  '/crm': typeof CrmRoute
  '/cs': typeof CsRoute
  '/dokumen': typeof DokumenRoute
  '/feedback': typeof FeedbackRoute
  '/galeri': typeof GaleriRoute
  '/hak-akses': typeof HakAksesRoute
  '/hotel': typeof HotelRoute
  '/itinerari': typeof ItinerariRoute
  '/keberangkatan': typeof KeberangkatanRoute
  '/komisi': typeof KomisiRoute
  '/laporan': typeof LaporanRoute
  '/laporan-keuangan': typeof LaporanKeuanganRoute
  '/loyalitas': typeof LoyalitasRoute
  '/panduan': typeof PanduanRoute
  '/pembayaran': typeof PembayaranRoute
  '/penerbangan': typeof PenerbanganRoute
  '/pengaturan': typeof PengaturanRoute
  '/pengeluaran': typeof PengeluaranRoute
  '/pengumuman': typeof PengumumanRoute
  '/portal-jamaah': typeof PortalJamaahRoute
  '/referral': typeof ReferralRoute
  '/sertifikat': typeof SertifikatRoute
  '/tour-leader': typeof TourLeaderRoute
  '/transportasi': typeof TransportasiRoute
  '/visa': typeof VisaRoute
  '/jamaah/$id': typeof JamaahIdRoute
  '/paket/$id': typeof PaketIdRoute
  '/jamaah': typeof JamaahIndexRoute
  '/paket': typeof PaketIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agen': typeof AgenRoute
  '/agensi': typeof AgensiRoute
  '/auth': typeof AuthRoute
  '/booking': typeof BookingRoute
  '/crm': typeof CrmRoute
  '/cs': typeof CsRoute
  '/dokumen': typeof DokumenRoute
  '/feedback': typeof FeedbackRoute
  '/galeri': typeof GaleriRoute
  '/hak-akses': typeof HakAksesRoute
  '/hotel': typeof HotelRoute
  '/itinerari': typeof ItinerariRoute
  '/keberangkatan': typeof KeberangkatanRoute
  '/komisi': typeof KomisiRoute
  '/laporan': typeof LaporanRoute
  '/laporan-keuangan': typeof LaporanKeuanganRoute
  '/loyalitas': typeof LoyalitasRoute
  '/panduan': typeof PanduanRoute
  '/pembayaran': typeof PembayaranRoute
  '/penerbangan': typeof PenerbanganRoute
  '/pengaturan': typeof PengaturanRoute
  '/pengeluaran': typeof PengeluaranRoute
  '/pengumuman': typeof PengumumanRoute
  '/portal-jamaah': typeof PortalJamaahRoute
  '/referral': typeof ReferralRoute
  '/sertifikat': typeof SertifikatRoute
  '/tour-leader': typeof TourLeaderRoute
  '/transportasi': typeof TransportasiRoute
  '/visa': typeof VisaRoute
  '/jamaah/$id': typeof JamaahIdRoute
  '/paket/$id': typeof PaketIdRoute
  '/jamaah/': typeof JamaahIndexRoute
  '/paket/': typeof PaketIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agen'
    | '/agensi'
    | '/auth'
    | '/booking'
    | '/crm'
    | '/cs'
    | '/dokumen'
    | '/feedback'
    | '/galeri'
    | '/hak-akses'
    | '/hotel'
    | '/itinerari'
    | '/keberangkatan'
    | '/komisi'
    | '/laporan'
    | '/laporan-keuangan'
    | '/loyalitas'
    | '/panduan'
    | '/pembayaran'
    | '/penerbangan'
    | '/pengaturan'
    | '/pengeluaran'
    | '/pengumuman'
    | '/portal-jamaah'
    | '/referral'
    | '/sertifikat'
    | '/tour-leader'
    | '/transportasi'
    | '/visa'
    | '/jamaah/$id'
    | '/paket/$id'
    | '/jamaah/'
    | '/paket/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agen'
    | '/agensi'
    | '/auth'
    | '/booking'
    | '/crm'
    | '/cs'
    | '/dokumen'
    | '/feedback'
    | '/galeri'
    | '/hak-akses'
    | '/hotel'
    | '/itinerari'
    | '/keberangkatan'
    | '/komisi'
    | '/laporan'
    | '/laporan-keuangan'
    | '/loyalitas'
    | '/panduan'
    | '/pembayaran'
    | '/penerbangan'
    | '/pengaturan'
    | '/pengeluaran'
    | '/pengumuman'
    | '/portal-jamaah'
    | '/referral'
    | '/sertifikat'
    | '/tour-leader'
    | '/transportasi'
    | '/visa'
    | '/jamaah/$id'
    | '/paket/$id'
    | '/jamaah'
    | '/paket'
  id:
    | '__root__'
    | '/'
    | '/agen'
    | '/agensi'
    | '/auth'
    | '/booking'
    | '/crm'
    | '/cs'
    | '/dokumen'
    | '/feedback'
    | '/galeri'
    | '/hak-akses'
    | '/hotel'
    | '/itinerari'
    | '/keberangkatan'
    | '/komisi'
    | '/laporan'
    | '/laporan-keuangan'
    | '/loyalitas'
    | '/panduan'
    | '/pembayaran'
    | '/penerbangan'
    | '/pengaturan'
    | '/pengeluaran'
    | '/pengumuman'
    | '/portal-jamaah'
    | '/referral'
    | '/sertifikat'
    | '/tour-leader'
    | '/transportasi'
    | '/visa'
    | '/jamaah/$id'
    | '/paket/$id'
    | '/jamaah/'
    | '/paket/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgenRoute: typeof AgenRoute
  AgensiRoute: typeof AgensiRoute
  AuthRoute: typeof AuthRoute
  BookingRoute: typeof BookingRoute
  CrmRoute: typeof CrmRoute
  CsRoute: typeof CsRoute
  DokumenRoute: typeof DokumenRoute
  FeedbackRoute: typeof FeedbackRoute
  GaleriRoute: typeof GaleriRoute
  HakAksesRoute: typeof HakAksesRoute
  HotelRoute: typeof HotelRoute
  ItinerariRoute: typeof ItinerariRoute
  KeberangkatanRoute: typeof KeberangkatanRoute
  KomisiRoute: typeof KomisiRoute
  LaporanRoute: typeof LaporanRoute
  LaporanKeuanganRoute: typeof LaporanKeuanganRoute
  LoyalitasRoute: typeof LoyalitasRoute
  PanduanRoute: typeof PanduanRoute
  PembayaranRoute: typeof PembayaranRoute
  PenerbanganRoute: typeof PenerbanganRoute
  PengaturanRoute: typeof PengaturanRoute
  PengeluaranRoute: typeof PengeluaranRoute
  PengumumanRoute: typeof PengumumanRoute
  PortalJamaahRoute: typeof PortalJamaahRoute
  ReferralRoute: typeof ReferralRoute
  SertifikatRoute: typeof SertifikatRoute
  TourLeaderRoute: typeof TourLeaderRoute
  TransportasiRoute: typeof TransportasiRoute
  VisaRoute: typeof VisaRoute
  JamaahIdRoute: typeof JamaahIdRoute
  PaketIdRoute: typeof PaketIdRoute
  JamaahIndexRoute: typeof JamaahIndexRoute
  PaketIndexRoute: typeof PaketIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agen': {
      id: '/agen'
      path: '/agen'
      fullPath: '/agen'
      preLoaderRoute: typeof AgenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agensi': {
      id: '/agensi'
      path: '/agensi'
      fullPath: '/agensi'
      preLoaderRoute: typeof AgensiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cs': {
      id: '/cs'
      path: '/cs'
      fullPath: '/cs'
      preLoaderRoute: typeof CsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dokumen': {
      id: '/dokumen'
      path: '/dokumen'
      fullPath: '/dokumen'
      preLoaderRoute: typeof DokumenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeri': {
      id: '/galeri'
      path: '/galeri'
      fullPath: '/galeri'
      preLoaderRoute: typeof GaleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hak-akses': {
      id: '/hak-akses'
      path: '/hak-akses'
      fullPath: '/hak-akses'
      preLoaderRoute: typeof HakAksesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel': {
      id: '/hotel'
      path: '/hotel'
      fullPath: '/hotel'
      preLoaderRoute: typeof HotelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itinerari': {
      id: '/itinerari'
      path: '/itinerari'
      fullPath: '/itinerari'
      preLoaderRoute: typeof ItinerariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keberangkatan': {
      id: '/keberangkatan'
      path: '/keberangkatan'
      fullPath: '/keberangkatan'
      preLoaderRoute: typeof KeberangkatanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/komisi': {
      id: '/komisi'
      path: '/komisi'
      fullPath: '/komisi'
      preLoaderRoute: typeof KomisiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan': {
      id: '/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof LaporanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan-keuangan': {
      id: '/laporan-keuangan'
      path: '/laporan-keuangan'
      fullPath: '/laporan-keuangan'
      preLoaderRoute: typeof LaporanKeuanganRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loyalitas': {
      id: '/loyalitas'
      path: '/loyalitas'
      fullPath: '/loyalitas'
      preLoaderRoute: typeof LoyalitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panduan': {
      id: '/panduan'
      path: '/panduan'
      fullPath: '/panduan'
      preLoaderRoute: typeof PanduanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pembayaran': {
      id: '/pembayaran'
      path: '/pembayaran'
      fullPath: '/pembayaran'
      preLoaderRoute: typeof PembayaranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/penerbangan': {
      id: '/penerbangan'
      path: '/penerbangan'
      fullPath: '/penerbangan'
      preLoaderRoute: typeof PenerbanganRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengaturan': {
      id: '/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof PengaturanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengeluaran': {
      id: '/pengeluaran'
      path: '/pengeluaran'
      fullPath: '/pengeluaran'
      preLoaderRoute: typeof PengeluaranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengumuman': {
      id: '/pengumuman'
      path: '/pengumuman'
      fullPath: '/pengumuman'
      preLoaderRoute: typeof PengumumanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal-jamaah': {
      id: '/portal-jamaah'
      path: '/portal-jamaah'
      fullPath: '/portal-jamaah'
      preLoaderRoute: typeof PortalJamaahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referral': {
      id: '/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof ReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sertifikat': {
      id: '/sertifikat'
      path: '/sertifikat'
      fullPath: '/sertifikat'
      preLoaderRoute: typeof SertifikatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tour-leader': {
      id: '/tour-leader'
      path: '/tour-leader'
      fullPath: '/tour-leader'
      preLoaderRoute: typeof TourLeaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transportasi': {
      id: '/transportasi'
      path: '/transportasi'
      fullPath: '/transportasi'
      preLoaderRoute: typeof TransportasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visa': {
      id: '/visa'
      path: '/visa'
      fullPath: '/visa'
      preLoaderRoute: typeof VisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jamaah/': {
      id: '/jamaah/'
      path: '/jamaah'
      fullPath: '/jamaah/'
      preLoaderRoute: typeof JamaahIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jamaah/$id': {
      id: '/jamaah/$id'
      path: '/jamaah/$id'
      fullPath: '/jamaah/$id'
      preLoaderRoute: typeof JamaahIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paket/': {
      id: '/paket/'
      path: '/paket'
      fullPath: '/paket/'
      preLoaderRoute: typeof PaketIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paket/$id': {
      id: '/paket/$id'
      path: '/paket/$id'
      fullPath: '/paket/$id'
      preLoaderRoute: typeof PaketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgenRoute: AgenRoute,
  AgensiRoute: AgensiRoute,
  AuthRoute: AuthRoute,
  BookingRoute: BookingRoute,
  CrmRoute: CrmRoute,
  CsRoute: CsRoute,
  DokumenRoute: DokumenRoute,
  FeedbackRoute: FeedbackRoute,
  GaleriRoute: GaleriRoute,
  HakAksesRoute: HakAksesRoute,
  HotelRoute: HotelRoute,
  ItinerariRoute: ItinerariRoute,
  KeberangkatanRoute: KeberangkatanRoute,
  KomisiRoute: KomisiRoute,
  LaporanRoute: LaporanRoute,
  LaporanKeuanganRoute: LaporanKeuanganRoute,
  LoyalitasRoute: LoyalitasRoute,
  PanduanRoute: PanduanRoute,
  PembayaranRoute: PembayaranRoute,
  PenerbanganRoute: PenerbanganRoute,
  PengaturanRoute: PengaturanRoute,
  PengeluaranRoute: PengeluaranRoute,
  PengumumanRoute: PengumumanRoute,
  PortalJamaahRoute: PortalJamaahRoute,
  ReferralRoute: ReferralRoute,
  SertifikatRoute: SertifikatRoute,
  TourLeaderRoute: TourLeaderRoute,
  TransportasiRoute: TransportasiRoute,
  VisaRoute: VisaRoute,
  JamaahIdRoute: JamaahIdRoute,
  PaketIdRoute: PaketIdRoute,
  JamaahIndexRoute: JamaahIndexRoute,
  PaketIndexRoute: PaketIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}